# Generated by Django 4.2.5 on 2023-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassMTMStudent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Paid_for', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='CustomClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('category', models.CharField(choices=[('other', 'Other'), ('cloth', 'Cloth'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('electronic', 'Electronic'), ('furniture', 'furniture')], default='other', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
