# Generated by Django 4.2.5 on 2023-09-28 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomClasses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customclass',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='enrolled_classes', through='CustomClasses.ClassMTMStudent', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customclass',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taught_classes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='classmtmstudent',
            name='custom_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_students', to='CustomClasses.customclass'),
        ),
        migrations.AddField(
            model_name='classmtmstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_classes', to=settings.AUTH_USER_MODEL),
        ),
    ]
