# Generated by Django 4.2.5 on 2023-09-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomClasses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmtmstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customclass',
            name='category',
            field=models.CharField(choices=[('other', 'Other'), ('cloth', 'Cloth'), ('laptop', 'Laptop'), ('mobile', 'Mobile'), ('electronic', 'Electronic'), ('furniture', 'Furniture')], default='other', max_length=20),
        ),
        migrations.AlterField(
            model_name='customclass',
            name='students',
            field=models.ManyToManyField(blank=True, through='CustomClasses.ClassMTMStudent', to=settings.AUTH_USER_MODEL),
        ),
    ]
