# Generated by Django 4.2.5 on 2023-09-28 11:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('CustomClasses', '0003_alter_classmtmstudent_student_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classmtmstudent',
            name='custom_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to='CustomClasses.customclass'),
        ),
        migrations.AlterField(
            model_name='classmtmstudent',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ps', to=settings.AUTH_USER_MODEL),
        ),
    ]
