# Generated by Django 4.2.5 on 2023-09-28 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomClasses', '0004_alter_classmtmstudent_custom_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclass',
            name='name',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
