# Generated by Django 4.2.5 on 2023-09-28 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CustomClasses', '0006_customclass_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customclass',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
