# Generated by Django 4.2.5 on 2023-09-28 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUserPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_Teacher', models.BooleanField(default=False)),
                ('is_Student', models.BooleanField(default=False)),
            ],
        ),
    ]
